api_version = "2025-07"

[[extensions]]
name = "t:name"
handle = "sales-cart-transform"
type = "function"
uid = "d285fcf0-cb43-035c-784d-f2aaf703eb6848509b14"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.transform.run"
  input_query = "src/cart_transform_run.graphql"
  export = "cart-transform-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui.paths]
  create = "/"
  details = "/"
